- name: variables from Play level
  hosts: localhost
  vars:
    course: "devops"
    trainer: "siva"
  tasks: 
    -name: check variables
    ansible.builtin.debug:
      msg:"hello I am learning {{course}} and trainer is {{trainer}}"