# task level variables
- name: variables from Play level
  hosts: localhost
  vars:
    course: "devops"
    trainer: "sivakumar"
  tasks: 
    - name: check variables
      vars: 
        course: devops with AWS
      ansible.builtin.debug:
        msg: "hello I am learning {{course}} and trainer is {{trainer}}"