- name: variables from Play level
  hosts: localhost
  tasks: 
  - name: check variables
    ansible.builtin.debug:
      msg: "hello {{PERSON}}, Good {{WISHES}}"



# ansible-playbook -i inventory -e ansible_user=centos -e ansible_password=DevOps321 
# -e "PERSON=SIVA" -e "WISHES=MRG" 09-vars_from_args.yamlclear