- name: variables from Play level
  hosts: localhost
  vars_files:
    - variables.yaml
  vars_prompt:
    - name: PERSON
      prompt: please enter your name
      private: false
    - name: WISHES
      prompt: please enter your wishes
      private: false
  vars: 
    PERSON: "VARUN from play"
    WISHES: "MRG from play"
  tasks: 
  - name: check variables
    vars: 
      PERSON: "VARUN from task"
      WISHES: "MRG from task"
    ansible.builtin.debug:
      msg: "hello {{PERSON}}, Good {{WISHES}}"


# first pref is command line args, second pref is task level vars, third pref is from file level,
# fourth pref is from prompt level, fifth pref is from play level, sixth pref is from inventory level.