- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: print person
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - git
        - mysql
        - postfix